services:
  - type: web
    name: ai-exam
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CAL:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    # 新增 apt 區塊以安裝必要的系統套件
    apt:
      packages:
        - libsentencepiece-dev
        - pkg-config