services:
  - type: web
    name: ai-exam
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CAL:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
