services:
  - type: web
    name: ni-exan
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CAL:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    apt:  # 確保 apt: 的縮排與 envVars: 一致
      packages:
        - libsentencepiece-dev
        - pkg-config